---
- name: copy nginx software
  copy: src=nginx.tar.gz dest=/tmp/nginx.tar.gz owner=root group=root mode=0755
- name: uncompression nginx software
  shell: tar xf /tmp/nginx.tar.gz -C /usr/local
- name: copy nginx start script
  template: src=nginx dest=/etc/init.d/nginx owner=root group=root mode=0755
- name: copy nginx config
  template: src=nginx.conf dest=/usr/local/nginx/conf/ owner=root group=root mode=0644
- name: mkdir
  shell: mkdir -p /data/wwwroot/www.wen.com
- name: touch
  shell: echo "wen.com" >> /data/wwwroot/www.wen.com/index.html
